In [1]:
import numpy as np

#### Use the following code for the questions below:

In [2]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

#### How many negative numbers are there?

In [5]:
mask = (a < 0)
mask

array([False, False, False, False,  True,  True, False, False, False,
        True, False,  True])

In [6]:
a[mask]

array([-2, -1, -6, -7])

In [9]:
mask.sum()

4

In [7]:
len(a[mask])

4

#### How many positive numbers are there?

In [12]:
a [a > 0]

array([ 4, 10, 12, 23,  3])

In [14]:
len(a [a > 0])

5

#### How many even positive numbers are there?

In [20]:
a [(a % 2 == 0) & (a > 0)]

array([ 4, 10, 12])

#### If you were to add 3 to each data point, how many positive numbers would there be?

In [23]:
b = a + 3
b

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [25]:
b [b > 0]

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3,  6])

In [26]:
len(b [b > 0])

10

#### If you squared each number, what would the new mean and standard deviation be?

In [35]:
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [51]:
(a ** 2).mean()

74.0

In [37]:
(a ** 2).std()

144.0243035046516

#### A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

In [38]:
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [40]:
a_mean = a.mean()
a_mean

3.0

In [50]:
np.mean(a)

3.0

In [41]:
a - a_mean

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [42]:
(a - a_mean).mean()

0.0

#### Calculate the z-score for each data point. Recall that the z-score is given by:

Z = (x − μ) / σ

In [43]:
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [53]:
a.mean()

3.0

In [46]:
a.std()

8.06225774829855

In [55]:
(a - a.mean()) / a.std()

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

### Setup 1

In [73]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#### Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [74]:
sum(a)

55

#### Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [75]:
min(a)

1

#### Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [76]:
max(a)

10

#### Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [78]:
sum(a) / len(a)

5.5

#### Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [161]:
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number
product_of_b

20160

#### Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [162]:
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)
squares_of_b

[9, 16, 25, 36, 49, 64]

#### Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

In [163]:
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
odds_in_b

[3, 5, 7]

#### Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

In [164]:
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
evens_in_b

[4, 6, 8]

### Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.

In [81]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]
b

[[3, 4, 5], [6, 7, 8]]

In [83]:
b = np.array(b)

#### Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. 

In [5]:
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)

In [84]:
np.sum(b)

33

#### Exercise 2 - refactor the following to use numpy. 

In [85]:
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

In [86]:
np.min(b)

3

#### Exercise 3 - refactor the following maximum calculation to find the answer with numpy.

In [87]:
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

In [88]:
np.max(b)

8

#### Exercise 4 - refactor the following using numpy to find the mean of b

In [89]:
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

In [90]:
np.average(b)

5.5

In [91]:
np.mean(b)

5.5

#### Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.

In [92]:
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

In [93]:
np.prod(b)

20160

In [94]:
np.product(b)

20160

#### Exercise 6 - refactor the following to use numpy to find the list of squares 

In [95]:
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)

In [98]:
b

array([[3, 4, 5],
       [6, 7, 8]])

In [97]:
b ** 2

array([[ 9, 16, 25],
       [36, 49, 64]])

#### Exercise 7 - refactor using numpy to determine the odds_in_b

In [103]:
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)

In [104]:
b [b % 2 == 1]

array([3, 5, 7])

#### Exercise 8 - refactor the following to use numpy to filter only the even numbers

In [105]:
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)

In [106]:
b [b % 2 == 0]

array([4, 6, 8])

#### Exercise 9 - print out the shape of the array b.

In [108]:
b.shape

(2, 3)

#### Exercise 10 - transpose the array b.

In [109]:
b

array([[3, 4, 5],
       [6, 7, 8]])

In [117]:
b.T

array([[3, 6],
       [4, 7],
       [5, 8]])

In [111]:
np.transpose(b)

array([[3, 6],
       [4, 7],
       [5, 8]])

#### Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

In [114]:
b.reshape(1,6)

array([[3, 4, 5, 6, 7, 8]])

#### Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [115]:
b.reshape(6,1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

### Setup 3

In [118]:
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
c

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [120]:
c = np.array(c)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Exercise 1 - Find the min, max, sum, and product of c.

In [121]:
c.min(), c.max(), c.prod()

(1, 9, 362880)

#### Exercise 2 - Determine the standard deviation of c.

In [122]:
c.std()

2.581988897471611

#### Exercise 3 - Determine the variance of c.

In [123]:
c.var()

6.666666666666667

#### Exercise 4 - Print out the shape of the array c

In [124]:
c.shape

(3, 3)

#### Exercise 5 - Transpose c and print out transposed result.

In [125]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [126]:
c.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

#### Exercise 6 - Get the dot product of the array c with c. 

In [127]:
np.dot(c,c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

#### Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

In [131]:
(c.T * c).sum()

261

#### Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [135]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [136]:
c.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [137]:
c*c.T

array([[ 1,  8, 21],
       [ 8, 25, 48],
       [21, 48, 81]])

In [134]:
(c * c.T).prod()

131681894400

### Setup 4

In [138]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]
d

[[90, 30, 45, 0, 120, 180],
 [45, -90, -30, 270, 90, 0],
 [60, 45, -45, 90, -45, 180]]

In [140]:
d = np.array(d)
d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

#### Exercise 1 - Find the sine of all the numbers in d

In [142]:
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

#### Exercise 2 - Find the cosine of all the numbers in d

In [143]:
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

#### Exercise 3 - Find the tangent of all the numbers in d

In [144]:
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

#### Exercise 4 - Find all the negative numbers in d

In [147]:
d [d < 0]

array([-90, -30, -45, -45])

#### Exercise 5 - Find all the positive numbers in d

In [148]:
d [d > 0 ]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

#### Exercise 6 - Return an array of only the unique numbers in d.

In [150]:
d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [151]:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

#### Exercise 7 - Determine how many unique numbers there are in d.

In [152]:
len(np.unique(d))

11

#### Exercise 8 - Print out the shape of d.

In [154]:
d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [153]:
d.shape

(3, 6)

#### Exercise 9 - Transpose and then print out the shape of d.

In [155]:
d.T

array([[ 90,  45,  60],
       [ 30, -90,  45],
       [ 45, -30, -45],
       [  0, 270,  90],
       [120,  90, -45],
       [180,   0, 180]])

In [156]:
d.T.shape

(6, 3)

#### Exercise 10 - Reshape d into an array of 9 x 2

In [159]:
d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [158]:
d.reshape(9,2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])